### ISSUE TITLE
Fetch Information doesn't work

### ISSUE THREAD

**Issue by teefixx** [PwnedC99/MultiChecker#5]
When I click on "Fetch Information from device" it turns white for 1 second but nothing happens. No information fetched.

iPhone 7
iOS 12.4
unc0ver 3.63

MacOS 10.14.6
MultiChecker Public Beta 2

**Comment by PwnedC99** [comment]
I am currently working on this. Get the newest release please and also make sure to configure your setup before fetching the device info.
